### ISSUE TITLE
Undefined macro error by executing autogen.sh

### ISSUE THREAD

**Issue by mahlzahn** [j4tools/j4status-plugins#3]
I get following output:
used both autoconf 2.68 & 2.69
```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.aux'.
libtoolize: copying file `.aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:13: error: possibly undefined macro: AC_ARG_VAR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:22: error: possibly undefined macro: AC_PATH_PROG
configure.ac:24: error: possibly undefined macro: AC_MSG_ERROR
configure:11940: error: possibly undefined macro: PKG_CHECK_MODULES
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
Thanks
mahlzahn

**Comment by Grimblee** [comment]
Hello, I also got an autogen.sh error when trying to build j4status_plugins:

libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `.aux'.
libtoolize: copying file `.aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:13: error: possibly undefined macro: AC_ARG_VAR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:22: error: possibly undefined macro: AC_PATH_PROG
configure.ac:24: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:29: error: possibly undefined macro: AC_SUBST
configure:12027: error: possibly undefined macro: PKG_CHECK_MODULES
configure:12043: error: possibly undefined macro: AC_CHECK_HEADERS
configure:12044: error: possibly undefined macro: AC_SEARCH_LIBS
autoreconf2.50: /usr/bin/autoconf failed with exit status: 1

Similar but not exactly the same so posted it :)
I had a similar error with autogen.sh for j4status, which was resolved by installing libtool.

Thanks for your time !

**Comment by sardemff7** [comment]
Could you try to run `ACLOCAL_FLAGS='-I /usr/local/share/aclocal' ./autogen.sh`?

**Comment by sardemff7** [comment]
I pushed 98f031060d3fbfb1a872701b6bbfbbbcd32d26e5 to make clear in a README that you may need two variables so that Autotools/pkg-config will find everything.

**Comment by kode54** [comment]
Has this changed, now that j4status has switched to using Meson?

**Comment by sardemff7** [comment]
For the aclocal part, yes, I will copy the `.m4` file in j4status-plugins directly for now. The pkg-config file is still the same.

I will migrate j4status-plugins to Meson at some point.
